# Generated by Django 5.1.3 on 2024-11-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="歌曲名字")),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="歌曲简介"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="music/static/", verbose_name="歌曲图片"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="歌曲链接")),
            ],
        ),
    ]
