# Generated by Django 5.1.3 on 2024-11-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="listenAgain",
            new_name="watchAgain",
        ),
    ]
